version: "3"

vars:
  GIT_REV:
    sh: git -c safe.directory={{.ROOT_DIR}}  rev-parse --short HEAD
  REGISTRY: 362159410824.dkr.ecr.us-east-2.amazonaws.com
  REPOSITORY: "k3auto"
  IMAGE_TAG: "testing-{{.GIT_REV}}"
  IMAGE_REF: "{{.REGISTRY}}/{{.REPOSITORY}}:{{.IMAGE_TAG}}"

tasks:
  rev: echo {{.GIT_REV}}
  image-ref: echo {{.IMAGE_REF}}

  run:
    cmds:
      - go run .

  test:
    cmds:
      - go test ./... -v --count=1

  hack:
    cmds:
      - go test ./hack/... -v --count=1

  e2e:
    cmds:
      - go test ./e2e/... -v --count=1

  docker-test-image:
    cmds:
      - >
        docker build . 
        -f testing.Dockerfile 
        -t {{.IMAGE_REF}}

  docker-test:
    cmds:
      - task: docker
        vars:
          DOCKER_CMD: task test

  docker-shell:
    cmds:
      - task: docker
        vars:
          DOCKER_CMD: /bin/bash
          DOCKER_RUN_EXTRA_FLAGS: "-i"

  docker:
    cmds:
      - task: docker-test-image
      - >
        docker run --rm -t
        {{.DOCKER_RUN_EXTRA_FLAGS}}
        --network host
        -v "/var/run/docker.sock:/var/run/docker.sock"
        -v "{{.ROOT_DIR}}:{{.ROOT_DIR}}"
        -w "{{.ROOT_DIR}}"
        {{.IMAGE_REF}}
        {{.DOCKER_CMD}}
