version: "3"

vars:
  REPO: 362159410824.dkr.ecr.us-east-2.amazonaws.com/k3auto
  GIT_REV:
    sh: git -c safe.directory={{.ROOT_DIR}}  rev-parse --short HEAD

tasks:
  rev: echo ${GIT_REV}

  run:
    cmds:
      - go run .

  test:
    cmds:
      - go test ./... -v --count=1

  hack:
    cmds:
      - go test ./hack/... -v --count=1

  e2e:
    cmds:
      - go test ./e2e/... -v --count=1

  docker-test-image:
    cmds:
      - >
        docker build . 
        -f testing.Dockerfile 
        -t {{.REPO}}:testing-{{.GIT_REV}}

  docker-test:
    cmds:
      - task: docker
        vars:
          DOCKER_CMD: task test

  docker-shell:
    cmds:
      - task: docker
        vars:
          DOCKER_CMD: /bin/bash
          DOCKER_RUN_EXTRA_FLAGS: "-i"

  docker:
    cmds:
      - task: docker-test-image
      - >
        docker run --rm -t
        {{.DOCKER_RUN_EXTRA_FLAGS}}
        --network host
        -v "/var/run/docker.sock:/var/run/docker.sock"
        -v "{{.ROOT_DIR}}:{{.ROOT_DIR}}"
        -w "{{.ROOT_DIR}}"
        {{.REPO}}:testing-{{.GIT_REV}}
        {{.DOCKER_CMD}}
