apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: k3auto
servers: 1
image: docker.io/rancher/k3s:v1.29.4-k3s1
kubeAPI:
  hostPort: "6443"

ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: 3m0s

  k3s:
    extraArgs:
      - arg: --disable=traefik,metrics-server
        nodeFilters:
          - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*

  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true

  runtime: {}
