apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: k3auto
servers: 1
image: docker.io/rancher/k3s:v1.29.1-k3s1
# network: bridge
kubeAPI:
  # host: host.docker.internal
  hostPort: "6443"

ports:
  - port: 8080:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: 3m0s
    # disableLoadbalancer: true

  k3s:
    extraArgs:
      - arg: --disable=traefik,metrics-server
        nodeFilters:
          - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*

  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true

  runtime: {}

registries:
  create:
    name: k3auto-registry
    hostPort: "8888"
