---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-state-metrics
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: kube-state-metrics
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
spec:
  chart:
    spec:
      chart: kube-state-metrics
      version: 4.0.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 15s
  values: {}
