---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana
  namespace: logging
spec:
  interval: 1m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  chart:
    spec:
      chart: loki-stack
      # version: 3.12.0
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 15s
  values:
    grafana:
      enabled: true
