apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  force: false
  interval: 10m0s
  path: /
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system-oci
    namespace: flux-system
