DefaultSecret: testsecreta
DefaultNamespace: default
Secrets:
  - Type: exec
    SecretName: "flux-system"
    SecretKey: "known-hosts"
    Args:
      - /bin/bash
      - -c
      - "aws ssm get-parameter --name /lab/flux-known-hosts --with-decryption | jq '.Parameter.Value'"

  - Type: exec
    SecretName: "flux-system"
    SecretKey: "flux-public-key"
    Args:
      - /bin/bash
      - -c
      - "aws ssm get-parameter --name /lab/flux-public-key --with-decryption | jq '.Parameter.Value'"
